name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build installer
        shell: pwsh
        run: ./build_installer.ps1

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: electroobra-installer
          path: Output/
          if-no-files-found: warn
